### ISSUE TITLE
Language tag normalization

### ISSUE THREAD

**Issue by Tpt** [Tpt/rio#8]
For downstream task, I believe it would be nice that the library normalizes language tags case.

If we do it, we should maybe use [RFC 5646](https://tools.ietf.org/html/rfc5646#section-2.1.1) format (i.e. lower case language code, upper case country code...).

@pchampin What do you think about it?

**Comment by pchampin** [comment]
I am not sure that the parser is the right place to perform this kind of normalization:

* implementers will still have to cope with denormalize language tags, because data could come from other sources than parsers (added programmatically) or other parsing libraries;
* end-users might be annoyed that the language tags in their data is tampered with (e.g. when parsing and serializing back).

If you really want to do it, I would go for the simple way: forcing the whole language tag to lowercase (since BCP47 states that they are case-insensitive anyway). Handling language code and country code differently, although it matches common practice, requires parsing the language tag, which is [complicated](https://stackoverflow.com/questions/7035825/regular-expression-for-a-language-tag-as-defined-by-bcp47).

**Comment by Tpt** [comment]
> implementers will still have to cope with denormalize language tags, because data could come from other sources than parsers (added programmatically) or other parsing libraries;

Indeed. It language tag case normalization is done by rio, rio should expose a function to do it.

> end-users might be annoyed that the language tags in their data is tampered with (e.g. when parsing and serializing back).

That's a very good point. Let's not do it as part of Rio. SPARQL requires the language code matching to be case insensitive so I going to normalize them to lower case in Rudf, approach suggested by [the RDF spec](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string). 


> Handling language code and country code differently, although it matches common practice, requires parsing the language tag, which is complicated.

The [RFC 5646 2.1.1](https://tools.ietf.org/html/rfc5646#section-2.1.1) suggest the following approach that is easy to implement:

> An implementation can reproduce this format without accessing the registry as follows.  All subtags, including extension and private use subtags, use lowercase letters with two exceptions: two-letter and four-letter subtags that neither appear at the start of the tag nor occur after singletons.  Such two-letter subtags are all uppercase (as in the tags "en-CA-x-ca" or "sgn-BE-FR") and four-letter subtags are titlecase (as in the tag "az-Latn-x-latn").

**Comment by pchampin** [comment]
> The RFC 5646 2.1.1 suggest the following approach that is easy to implement: (...)

Still significantly more complex than a dump lowercase :-)
